-- MySQL Script generated by MySQL Workbench
-- 06/06/16 16:27:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema presetsDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema presetsDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `presetsDatabase` ;
CREATE SCHEMA IF NOT EXISTS `presetsDatabase` ;
USE `presetsDatabase` ;

-- -----------------------------------------------------
-- Table `presetsDatabase`.`camera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`camera` (
  `ID` INT(11) NOT NULL,
  `MACaddress` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`IPpreset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`IPpreset` (
  `ID` INT(11) NOT NULL,
  `Pan` DOUBLE NULL DEFAULT NULL,
  `Tilt` DOUBLE NULL DEFAULT NULL,
  `Zoom` DOUBLE NULL DEFAULT NULL,
  `Focus` DOUBLE NULL DEFAULT NULL,
  `Iris` DOUBLE NULL DEFAULT NULL,
  `Autofocus` INT(11) NULL DEFAULT NULL,
  `Panspeed` DOUBLE NULL DEFAULT NULL,
  `Tiltspeed` DOUBLE NULL DEFAULT NULL,
  `Autoiris` INT(11) NULL DEFAULT NULL,
  `Image` CHAR(50) NULL DEFAULT '',
  `camera_ID` INT(11) NOT NULL,
  `name` CHAR(50) NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  INDEX `fk_preset_camera_idx` (`camera_ID` ASC),
  CONSTRAINT `fk_preset_camera`
    FOREIGN KEY (`camera_ID`)
    REFERENCES `presetsDatabase`.`camera` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`simplepreset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`simplepreset` (
  `ID` INT(11) NOT NULL,
  `Image` CHAR(50) NULL DEFAULT '',
  `camera_ID` INT(11) NOT NULL,
  `name` CHAR(50) NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  INDEX `fk_simplepreset_camera_idx` (`camera_ID` ASC),
  CONSTRAINT `fk_simplepreset_camera`
    FOREIGN KEY (`camera_ID`)
    REFERENCES `presetsDatabase`.`camera` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`tag` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`preset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`preset` (
  `ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`tagPreset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`tagPreset` (
  `preset_ID` INT(11) NOT NULL,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_name`, `preset_ID`),
  INDEX `fk_tagPreset_tag1_idx` (`tag_name` ASC),
  INDEX `fk_tagPreset_preset1_idx` (`preset_ID` ASC),
  CONSTRAINT `fk_tagPreset_tag1`
    FOREIGN KEY (`tag_name`)
    REFERENCES `presetsDatabase`.`tag` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagPreset_preset1`
    FOREIGN KEY (`preset_ID`)
    REFERENCES `presetsDatabase`.`preset` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`queue` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presetsDatabase`.`presetsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presetsDatabase`.`presetsList` (
  `Sequence` INT(11) NOT NULL,
  `queue_ID` INT(11) NOT NULL,
  `preset_ID` INT(11) NOT NULL,
  PRIMARY KEY (`queue_ID`, `preset_ID`, `Sequence`),
  INDEX `fk_presetsList_preset1_idx` (`preset_ID` ASC),
  CONSTRAINT `fk_presetsList_queue1`
    FOREIGN KEY (`queue_ID`)
    REFERENCES `presetsDatabase`.`queue` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presetsList_preset1`
    FOREIGN KEY (`preset_ID`)
    REFERENCES `presetsDatabase`.`preset` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
